# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "213979d0a92bef6823d1266742a03997"
name = "fragile-banner"
handle = "fragile-banner"
application_url = "https://curtis-play-sensor-rica.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dawn-customized-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://curtis-play-sensor-rica.trycloudflare.com/auth/callback",
  "https://curtis-play-sensor-rica.trycloudflare.com/auth/shopify/callback",
  "https://curtis-play-sensor-rica.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
